Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Calculate fibre volume fraction and phi
# vf = #input equation to calculate Vf based on FAW, t, fibre density
# phi = #input equation for porosity

print("vf =", round(vf,2))
print("phi =", round(phi,2))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[7], line 5[0m
[0;32m      1[0m [38;5;66;03m#Calculate fibre volume fraction and phi[39;00m
[0;32m      2[0m [38;5;66;03m# vf = #input equation to calculate Vf based on FAW, t, fibre density[39;00m
[0;32m      3[0m [38;5;66;03m# phi = #input equation for porosity[39;00m
[1;32m----> 5[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mvf =[39m[38;5;124m"[39m, [38;5;28mround[39m([43mvf[49m,[38;5;241m2[39m))
[0;32m      6[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mphi =[39m[38;5;124m"[39m, [38;5;28mround[39m(phi,[38;5;241m2[39m))

[1;31mNameError[0m: name 'vf' is not defined
NameError: name 'vf' is not defined

